language: node_js
node_js:
- 7.10.0
branches:
  only:
  - master

before_install:
- openssl aes-256-cbc -K $encrypted_ffc5f15538a8_key -iv $encrypted_ffc5f15538a8_iv
  -in qxm_key.enc -out ~/.ssh/qxm_key -d

# - mv qxm_key ~/.ssh -f
# 改变文件权限
- chmod 600 ~/.ssh/qxm_key

# 配置ssh
- eval $(ssh-agent)
- ssh-add ~/.ssh/qxm_key
- cp .travis/ssh_config ~/.ssh/config

after_script:
- scp -o StrictHostKeyChecking=no -r ./* root@qxmin.cn:/root/code/ci-code

addons:
  ssh_know_hosts: '47.94.217.105'


