language: node_js
node_js:
- 7.10.0
branches:
  only:
  - master
after_script:
- scp -o StrictHostKeyChecking=no app.js root@qxmin.cn:/code
before_install:
- openssl aes-256-cbc -K $encrypted_ffc5f15538a8_key -iv $encrypted_ffc5f15538a8_iv
  -in qxm_key.enc -out ~\/.ssh/qxm_key -d
